#!/usr/bin/env bash
# =============================================================================
# sync-agent-files.sh — generate the thin CLAUDE.md entry point beside AGENTS.md
# =============================================================================
# AGENTS.md is the source of truth for agent guidance: `agy` reads it natively,
# and so do most modern CLI agents. Claude Code reads CLAUDE.md. So every
# directory holding an AGENTS.md gets a generated five-line CLAUDE.md whose only
# content is an `@AGENTS.md` import.
#
# Generated files rather than symlinks. The sibling repo gives three reasons
# (Windows checkouts, IDE agent checkouts, zip exports); on this substrate only
# the last two are even theoretical, since both repos are checked out by git on
# APFS or ext4. The honest reason here is smaller and sufficient: a five-line
# stub is trivially regenerable, `--check` can lock it, and it leaves room for
# Claude-specific content later. It is a preference, not a portability
# requirement, and this comment exists so nobody re-derives a stronger one.
#
# TWO DIVERGENCES FROM THE SIBLING'S COPY, both deliberate:
#
#   1. IT REFUSES TO CLOBBER A REAL CLAUDE.md. The sibling's version does an
#      unconditional `cat >`, which is safe THERE only because its migration
#      already happened — its root CLAUDE.md is already the stub. Run verbatim
#      against a repo whose CLAUDE.md still holds real content (this one held
#      133 lines of load-bearing invariants until 2026-09-03), it silently
#      truncates it to five lines with no backup and no diff. The guard below
#      turns that into a refusal that names the migration.
#
#   2. IT EXCLUDES VENDORED TREES AND TEST FIXTURES. `find -name AGENTS.md`
#      matches more than repo guidance. Here it also matches:
#        * sandbox_templates/skills/myconv/.../templates/AGENTS.md — a payload
#          file INSIDE a vendored plugin. Writing beside it changes the tree
#          hash, so `just tools-check` reports DRIFT against the channel, and
#          the next `just vendor-tools` deletes the file again anyway.
#        * scripts/depaudit-fixtures/docs-injection/AGENTS.md — a test fixture
#          whose whole point is that an install command "lives only in
#          AGENTS.md". Adding a second instruction file to that directory
#          changes what the fixture is a fixture OF.
#      The sibling excludes only .git and docs/_archive, and carries both of
#      these files — so running its copy today would write into both.
#
# A legacy GEMINI.md is REPORTED, not deleted (the sibling deletes it). A script
# that removes a file the operator did not ask about is the shape ADR-0008 is
# about, even when the script is host-side.
#
# Idempotent. Run after adding, moving or editing any AGENTS.md:
#   scripts/sync-agent-files.sh            # write
#   scripts/sync-agent-files.sh --check    # verify only, exit 1 on drift
#
# bash 3.2 (macOS /usr/bin/env bash): no mapfile, no associative arrays.
# =============================================================================
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

MODE="write"
if [ $# -gt 0 ]; then
  case "$1" in
    --check) MODE="check" ;;
    -h|--help) sed -n '2,50p' "${BASH_SOURCE[0]}" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) printf 'sync-agent-files: unknown flag %s (valid: --check)\n' "$1" >&2; exit 1 ;;
  esac
fi

# The marker that identifies a file this script wrote. The guard keys off this
# string, so changing it orphans every already-generated stub — if it ever has
# to change, regenerate in the same commit.
MARKER='<!-- GENERATED by scripts/sync-agent-files.sh — edit AGENTS.md, not this file. -->'

stub() {
  printf '# CLAUDE.md\n\n%s\n\n@AGENTS.md\n' "$MARKER"
}

# Paths under which an AGENTS.md is NOT repo guidance. Space-padded membership
# test rather than an array, for bash 3.2.
EXCLUDE_PREFIXES=" sandbox_templates/skills/ scripts/depaudit-fixtures/ docs/_archive/ "

excluded() {  # <path relative to REPO_ROOT>
  local d="$1" p
  for p in $EXCLUDE_PREFIXES; do
    case "$d" in "$p"*) return 0 ;; esac
  done
  return 1
}

PASS=0
DRIFT=0
SKIPPED=0

sync_dir() {  # <dir relative to REPO_ROOT>
  local dir="$1" target want have
  if [ "$dir" = "." ]; then target="CLAUDE.md"; else target="$dir/CLAUDE.md"; fi

  if excluded "$dir"; then
    SKIPPED=$((SKIPPED + 1))
    printf '  skip  %-56s (not repo guidance)\n' "$dir/AGENTS.md"
    return 0
  fi

  want="$(stub)"

  # THE GUARD. An existing CLAUDE.md that this script did not write holds
  # content nobody asked us to destroy.
  if [ -f "$REPO_ROOT/$target" ] && ! grep -qF "$MARKER" "$REPO_ROOT/$target"; then
    printf '\n  REFUSING to overwrite %s\n' "$target" >&2
    printf '  It is not a generated stub: it has no GENERATED marker, so it holds\n' >&2
    printf '  content of its own (%s lines). This script would replace it with five\n' \
           "$(wc -l < "$REPO_ROOT/$target" | tr -d ' ')" >&2
    printf '  lines and keep no backup.\n\n' >&2
    printf '  Migrate first, by hand:\n' >&2
    printf '    git mv %s %s\n' "$target" "${target%CLAUDE.md}AGENTS.md" >&2
    printf '    (merge, if an AGENTS.md is already there), then re-run this.\n\n' >&2
    exit 1
  fi

  have=""
  [ -f "$REPO_ROOT/$target" ] && have="$(cat "$REPO_ROOT/$target")"

  if [ "$have" = "$want" ]; then
    PASS=$((PASS + 1))
    printf '  ok    %s\n' "$target"
    return 0
  fi

  DRIFT=$((DRIFT + 1))
  if [ "$MODE" = "check" ]; then
    if [ -z "$have" ]; then
      printf '  DRIFT %-56s (missing)\n' "$target" >&2
    else
      printf '  DRIFT %-56s (stale)\n' "$target" >&2
    fi
    return 0
  fi

  stub > "$REPO_ROOT/$target"
  printf '  wrote %s\n' "$target"
}

cd "$REPO_ROOT"

# find -print0 into `read -r -d ''`: no mapfile, and filenames with spaces
# survive. Process substitution keeps the counters in THIS shell, which a pipe
# would not (the loop body would run in a subshell and every count would be 0 —
# the same vacuous-pass shape as bash 3.2's missing mapfile).
while IFS= read -r -d '' f; do
  sync_dir "$(dirname "${f#./}")"
done < <(find . -name AGENTS.md -not -path './.git/*' -print0 | sort -z)

# A legacy GEMINI.md is reported, never removed.
while IFS= read -r -d '' g; do
  printf '  NOTE  %s is legacy — agy reads AGENTS.md natively. Remove it by hand.\n' \
         "${g#./}" >&2
done < <(find . -name GEMINI.md -not -path './.git/*' -print0)

printf '\n  %d in sync, %d drifted, %d skipped\n' "$PASS" "$DRIFT" "$SKIPPED"

if [ "$MODE" = "check" ] && [ "$DRIFT" -gt 0 ]; then
  printf '  run: scripts/sync-agent-files.sh\n' >&2
  exit 1
fi
exit 0
